### ISSUE TITLE
IP TCL is not working on DALnet

### ISSUE THREAD

**Issue by fahadmehar** [MadaliNTCL/eggdrop-tcl#1]
< [09:44:44] couldn't read file "scripts/IP2.tcl": no such file or directory
<     while executing
< "source scripts/IP2.tcl"
<     (file "eggdrop.conf" line 208)

Tcl error [ip:main]: invalid command name "json::json2dict"

**Comment by MadaliNTCL** [comment]
Install package 'dict' from user root on your server.

**yum install dict** or **apt-get install dict** depending on you OS
